blank_issues_enabled: false
contact_links:
  - name: ğŸ“ƒ User documentation
    url: https://docs.unchainex.org/
    about: Search for any information about Unchainex.
  - name: ğŸ’ª Community support
    url: https://github.com/Unchainex/Wallet/discussions/categories/support
    about: Feel free to ask anything.
  - name: â“ Other issue?
    url: https://github.com/Unchainex/Wallet/discussions/
    about: Search on the community forum.
